
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class home extends javax.swing.JFrame {
    public int i=0;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_two_arrow = new javax.swing.JButton();
        btn_add_patient = new javax.swing.JButton();
        btn_add_diagnosis = new javax.swing.JButton();
        btn_fullHistory = new javax.swing.JButton();
        btn_update_patient = new javax.swing.JButton();
        btn_hospital_info = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_two_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/two arrow.png"))); // NOI18N
        btn_two_arrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_two_arrowActionPerformed(evt);
            }
        });
        getContentPane().add(btn_two_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btn_add_patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient.png"))); // NOI18N
        btn_add_patient.setText(" Add New Patient");
        btn_add_patient.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_add_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_patientActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add_patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btn_add_diagnosis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add diag.png"))); // NOI18N
        btn_add_diagnosis.setText("Add Diagnosis Information ");
        btn_add_diagnosis.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_add_diagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_diagnosisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add_diagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btn_fullHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_history1.png"))); // NOI18N
        btn_fullHistory.setText("Patient Full History");
        btn_fullHistory.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_fullHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fullHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btn_fullHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btn_update_patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_update_details.png"))); // NOI18N
        btn_update_patient.setText("Update Patient Record");
        btn_update_patient.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_update_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_patientActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update_patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        btn_hospital_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_hospital_information.png"))); // NOI18N
        btn_hospital_info.setText("Hospital Information");
        btn_hospital_info.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_hospital_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hospital_infoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hospital_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_two_arrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_two_arrowActionPerformed
        // TODO add your handling code here:
        if(i==0)
        {
            btn_add_patient.setLocation(90, 30);
            btn_add_diagnosis.setLocation(333, 30);
            btn_fullHistory.setLocation(576, 30);
            btn_update_patient.setLocation(819, 30);
            btn_hospital_info.setLocation(1062, 30);
            btn_logout.setLocation(1062, 89);
            i=1;
        
        }
        else
        {
            btn_add_patient.setLocation(10, 107);
            btn_add_diagnosis.setLocation(10, 184);
            btn_fullHistory.setLocation(10, 261);
            btn_update_patient.setLocation(10, 338);
            btn_hospital_info.setLocation(10, 415);
            btn_logout.setLocation(10, 490);
            i=0;
        }
    }//GEN-LAST:event_btn_two_arrowActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
          setVisible(false);
          new login().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_add_diagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_diagnosisActionPerformed
        // TODO add your handling code here:
        new addDiagnosisInformation().setVisible(true);
    }//GEN-LAST:event_btn_add_diagnosisActionPerformed

    private void btn_fullHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fullHistoryActionPerformed
        // TODO add your handling code here:
        new fullHistoryOfThePatient().setVisible(true);
    }//GEN-LAST:event_btn_fullHistoryActionPerformed

    private void btn_update_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_patientActionPerformed
        // TODO add your handling code here:
        new updatePatientRecord().setVisible(true);
    }//GEN-LAST:event_btn_update_patientActionPerformed

    private void btn_hospital_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hospital_infoActionPerformed
        // TODO add your handling code here:
        new hospitalInformation().setVisible(true);
    }//GEN-LAST:event_btn_hospital_infoActionPerformed

    private void btn_add_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_patientActionPerformed
        // TODO add your handling code here:
        new addNewPatient().setVisible(true);
    }//GEN-LAST:event_btn_add_patientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_diagnosis;
    private javax.swing.JButton btn_add_patient;
    private javax.swing.JButton btn_fullHistory;
    private javax.swing.JButton btn_hospital_info;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_two_arrow;
    private javax.swing.JButton btn_update_patient;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
